### ISSUE TITLE
 New task definition not running within 90 seconds

### ISSUE THREAD

**Issue by BrunoQuaresma** [silinternational/ecs-deploy#100]
I try using this script but this message is displayed: 

Current task definition: arn:aws:ecs:us-east-1:444480608166:task-definition/auth:5
New task definition: arn:aws:ecs:us-east-1:444480608166:task-definition/auth:7
ERROR: New task definition not running within 90 seconds

**Comment by mewins-iwin** [comment]
We see this quite a lot also but we add the '-t' parameter to our build script and set to 300 seconds. We have found that gives ECS enough time to complete it's processing. Also inside the script it appears to poll ECS regularly so if it completes within 300 seconds (or whatever) then it will end the script in a reasonable time period and not block. Hope this helps.

**Comment by fillup** [comment]
Hi @BrunoQuaresma, as @mewins-iwin mentions, sometimes ECS is just slow with getting new tasks launched and ready. Sometimes it is really fast and other times it takes several minutes. To prevent failed builds due to ECS being slow I recommend you use the `-t` parameter to increase the timeout. I use `-t 300` just like @mewins-iwin and that seems to always be sufficient.
