### ISSUE TITLE
Finding an Issue while deploying ECS cluster

### ISSUE THREAD

**Issue by sahilsehgalinc** [silinternational/ecs-deploy#142]
Hi Pal, 
Thanks for providing such a great script, I am stuck with no clues at this stage, could you please give me any hint where I'm wrong?

----------------------------------------------------
root@ldap:/home/ubuntu# ecs-deploy -c default -n custom-service -i 755586615581.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
Using image name: 755586615581.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
Current task definition: arn:aws:ecs:us-east-1:755586615581:task-definition/first-run-task-definition:4

Parameter validation failed:
Unknown parameter in input: "placementConstraints", must be one of: family, taskRoleArn, networkMode, containerDefinitions, volumes
----------------------------------------------------------

Regards,
Sahil Sehgal

**Comment by sahilsehgalinc** [comment]
Another Issue I am encountering while execution of deployment script, it is not picking up the recent task definition and modifying cluster task, output as mentioned below:

-----------------------------------

+ sleep 10
+ i=590
+ '[' 590 -lt 600 ']'
++ /usr/bin/aws --output json ecs list-tasks --cluster sandbox-ecs --service-name pdf --desired-status RUNNING
++ jq -r '.taskArns[]'
+ RUNNING_TASKS=arn:aws:ecs:us-east-1:xxxxxxxxxxxx:task/c7xxxxda-axx6-4xx1-axx1-3a2xxxxxxxx2
+ [[ ! -z arn:aws:ecs:us-east-1:xxxxxxxxxxxx:task/c7xxxxda-axx6-4xx1-axx1-3a2xxxxxxxx2 ]]
++ /usr/bin/aws --output json ecs describe-tasks --cluster sandbox-ecs --tasks arn:aws:ecs:us-east-1:xxxxxxxxxxxx:task/c7xxxxda-axx6-4xx1-axx1-3a2xxxxxxxx2
++ jq '.tasks[]| if .taskDefinitionArn == "arn:aws:ecs:us-east-1:xxxxxxxxxxxx:task-definition/pdf:40" then . else empty end|.lastStatus'
++ grep -e RUNNING
+ RUNNING=
+ :
+ '[' '' ']'
+ sleep 10
+ i=600
+ '[' 600 -lt 600 ']'
+ [[ false != \t\r\u\e ]]
+ echo 'ERROR: New task definition not running within 600 seconds'
ERROR: New task definition not running within 600 seconds
+ [[ false != \f\a\l\s\e ]]
+ exit 1
---------------------------------------

Can you give me any hint on that?

**Comment by fillup** [comment]
@sahilsehgalinc a common cause of this is if you do not have enough resource capacity in your cluster for ECS to launch another instance of your task. ECS rolling updates will launch the new task definition and when it becomes healthy it'll start draining and replacing old versions with the new. If you don't have enough capacity for another instance though it can't launch it and therefore can't stop the current either. If for example you are running two instances of a task, you can set the minimum healthy percentage to 50 so that ECS will stop one in order to launch the new task definition version.
