### ISSUE TITLE
USE_MOST_RECENT_TASK_DEFINITION actually doesn't take the most recently task definition that was created

### ISSUE THREAD

**Issue by micha-bitton-walkme** [silinternational/ecs-deploy#214]
Hi,
When using "USE_MOST_RECENT_TASK_DEFINITION" flag it's actually doesn't take the most recent task definition that was created.

Scenario steps:
1. create new task definition for the service in the console, now task is on revision "2"
2. execute the command "ecs-deploy -c <cluster> -n <service> -i <image> -r <region> --use-latest-task-def"
outputs:
Using image name: <image>
Current task definition: the one that I created above
New task definition: creating new task definition.

after deep dive on the script I saw that it's "registering" always new task and the flag doesn't effect to avoid it:

according to the script it's should take the recent "TASK_DEFINITION_ARN" variable and not "NEW_DEF" variable.

**Comment by fillup** [comment]
It's been a while since I've been in that part of the code, but it looks to me like when `USE_MOST_RECENT_TASK_DEFINITION` is true, it gets the ARN for the newest version and uses it as the basis for creating a new task definition to apply to the service. So I believe you'll get the same configuration, just a new revision. If that isn't true or it's not working that way for you feel free to reopen.
