### ISSUE TITLE
Memory SoftLimit causes error

### ISSUE THREAD

**Issue by jeremypumphrey** [silinternational/ecs-deploy#62]
ECS service/task definitions require to either set Hard or Soft Memory limits. I've been using ecs-deploy successfully with hard (memory) limits, and when I just updated my task definition to soft (memoryReservation) limits I got this error the next time I tried to use ecs-deploy. I did have one of the two specified so I shouldn't be getting this error. I added a hard definition in addition to the soft one and it goes away. 

An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Invalid setting for container 'PatientAPI'. At least one of 'memory' or 'memoryReservation' must be specified.

**Comment by jeremypumphrey** [comment]
I also noticed that although I've defined both a soft and a hard memory limit, after I use ecs-deploy I lose the soft limit. Only the hard limit is transferred to the new task.

**Comment by fillup** [comment]
Interesting, I imagine the problem is with https://github.com/silinternational/ecs-deploy/blob/develop/ecs-deploy#L301. I'll have to play around with that line a bit and see what we're doing that is filtering the soft limit out.

**Comment by jeremypumphrey** [comment]
Thanks. I'd really like to just use the Soft limit setting and not the Hard limit at all

**Comment by fillup** [comment]
@jeremypumphrey I just tested this out and its working fine. It probably just requires an updated AWS CLI version. I believe you're using the Docker image right? Since I hadn't released updates for a little while it has probably just gotten behind on the AWS CLI version. I released `2.5.0` earlier today which added the desired count support, so there is an updated image in Docker Hub. I pulled the latest image down and tested it and its working now too :-)

**Comment by jeremypumphrey** [comment]
Confirmed fixed. Thanks!

**Comment by Lukewa** [comment]
Hey @fillup, i realised same problem as jeremy, but with version 2.6.1, so it should work right now.


`An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Invalid setting for container 'api-production'. At least one of 'memory' or 'memoryReservation' must be specified.`
