### ISSUE TITLE
Script Does not stop the tasks with previous revision

### ISSUE THREAD

**Issue by mspapant** [silinternational/ecs-deploy#85]
I am trying to use the script to deploy a new version in ecs but all the time i get:

> ERROR: New task definition not running within 90 seconds

Also, when i see the ecs console i can only see the task with the previous revision

**Comment by aliem** [comment]
`ecs-deploy` by default tries to do Blue Green deployments, it will not stop the previous running task.

I have a patch for an old version: https://gist.github.com/aliem/b04d189ca5a11aa54ee12971605e30a5

**Comment by fillup** [comment]
@mspapant @aliem `ecs-deploy` utilizes built in functionality in ECS for deploying new task definitions and killing old ones. It does not need to kill old tasks because ECS will do that after the new version is running and reaches a healthy status with the ELB. If you do not have enough capacity to start the new version you'll get the error you are seeing now, or if ECS is just slow at the time you may get that error. You can increase the timeout using the `-t` argument to give it more time to reach a running state. I've found it to vary pretty often and sometimes take even more than 5 minutes to get the new version running. 

@aliem I'm open to the functionality you have in your gist if you want to submit it as a pull request.

**Comment by Kostanos** [comment]
I agree with the green deploy, and it works well on several instances that I'm managing.
But in one particular case, when I have only one instance and tasks have "hardcoded" ports, they can't be updating without forcefully stop previous task first.
Can we add the option like: --force-stop-task? which will stop task automatically
